services:
  postgres:
    image: postgres:16-alpine
    container_name: platform_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin@123
      POSTGRES_DB: ksrDb
    ports:
      - "5432:5432"
    volumes:
      - platform_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: platform_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ksr.local
      PGADMIN_DEFAULT_PASSWORD: admin@123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  platform_pgdata:
